// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AvatarPreviewController from "./avatar_preview_controller"
application.register("avatar-preview", AvatarPreviewController)

import CarouselController from "./carousel_controller"
application.register("carousel", CarouselController)

import ItemEditController from "./item_edit_controller"
application.register("item-edit", ItemEditController)

import ItemNewController from "./item_new_controller"
application.register("item-new", ItemNewController)

import MapController from "./map_controller"
application.register("map", MapController)

import MenuController from "./menu_controller"
application.register("menu", MenuController)

import RecordController from "./record_controller"
application.register("record", RecordController)

import ReviewModalController from "./review_modal_controller"
application.register("review-modal", ReviewModalController)

import ShowMapController from "./show_map_controller"
application.register("show-map", ShowMapController)

import SwiperController from "./swiper_controller"
application.register("swiper", SwiperController)
